CREATE TABLE IF NOT EXISTS projects(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  priority integer NOT NULL,
  description text,
  deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL CHECK (name <> ''),
  done BOOLEAN,
  projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Make a Web App', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Make an App', 1, 'Using Dart', '2019-05-13');

INSERT INTO projects(name, priority, description, deliverydate)
  VALUES('Make a Desktop App', 2, 'Using C++', '2019-05-14');

-- INSERT TASKS DATA
INSERT INTO tasks(name, done, projectId)
  VALUES('download Vuejs', false, 1)

INSERT INTO tasks(name, done, projectId)
  VALUES('Create UI WEB', false, 1)

INSERT INTO tasks(name, done, projectId)
  VALUES('download Flutter', false, 2)

INSERT INTO tasks(name, done, projectId)
  VALUES('Design UI', false, 2)